In [22]:
import json
import pandas as pd
import datetime
with open("uber_all.json") as infile:
    tweet_uber = json.load(infile)

In [3]:
tweet_uber.keys()

dict_keys(['statuses', 'search_metadata'])

In [23]:
tw_text = [a['text'] for a in tweet_uber['statuses']]

In [5]:
#['#taxi' in a for a in tw_text]

In [24]:
df=pd.DataFrame()

In [25]:
date=pd.Series([datetime.datetime.strptime(a['created_at'],'%a %b %d %H:%M:%S %z %Y').strftime('%Y-%m-%d %H:00')
                for a in tweet_uber['statuses']])

In [26]:
token_list=['#taxi','#Taxi','#logo','#design','#uberlogo','#SuperBowl50','#SB50','#Paris',
            '#surgepricing',"#SurgePricing","#surge","surge pricing"]
for token in token_list:
    tokenseries=pd.Series([token in a for a in tw_text])
    df[token]=tokenseries
df['date']=date

In [27]:
df1=df.groupby(df['date']).sum()

In [28]:
df1

,#taxi,#Taxi,#logo,#design,#uberlogo,#SuperBowl50,#SB50,#Paris,#surgepricing,#SurgePricing,#surge,surge pricing
date,,,,,,,,,,,,
2016-01-20 19:00,2,0,0,0,0,0,0,0,0,0,0,0
2016-01-20 20:00,4,1,0,0,0,0,0,0,0,0,0,0
2016-01-20 21:00,4,2,0,0,0,0,0,0,0,0,0,0
2016-01-20 22:00,0,8,0,3,0,0,0,0,0,0,0,0
2016-01-20 23:00,3,1,0,0,0,0,0,0,0,0,1,0
2016-01-21 00:00,3,0,0,0,0,0,0,0,0,0,0,0
2016-01-21 01:00,3,0,0,0,0,0,2,0,0,0,0,0
2016-01-21 02:00,2,1,0,0,0,0,0,0,0,0,0,0
2016-01-21 03:00,2,0,0,0,0,0,1,0,0,0,1,0
2016-01-21 04:00,0,0,0,0,0,0,0,0,0,0,0,0
2016-01-21 05:00,0,0,0,0,0,0,0,0,0,0,0,0
2016-01-21 06:00,0,0,0,0,0,0,0,0,0,0,0,0
2016-01-21 07:00,0,0,0,0,0,0,0,0,0,0,0,0
2016-01-21 08:00,6,1,0,0,0,0,0,0,0,0,0,0
2016-01-21 09:00,3,2,0,0,0,0,0,0,0,0,0,0
2016-01-21 10:00,2,1,0,0,0,0,0,0,0,0,0,0
2016-01-21 11:00,5,2,0,0,0,0,0,0,0,0,0,0
2016-01-21 12:00,5,3,0,0,0,0,0,0,0,0,0,0
2016-01-21 13:00,3,0,0,0,0,0,0,0,0,0,0,1
2016-01-21 14:00,2,1,0,0,0,0,0,0,0,0,0,1
2016-01-21 15:00,0,0,0,0,0,1,0,0,0,0,0,0
2016-01-21 16:00,1,1,0,0,0,0,0,0,0,0,0,0
2016-01-21 17:00,2,3,0,0,0,0,0,0,0,0,0,0
2016-01-21 18:00,1,0,0,0,0,0,0,0,0,0,0,1
2016-01-21 19:00,1,0,0,0,0,0,0,0,0,0,0,0
2016-01-21 20:00,1,3,0,0,0,0,0,0,0,0,0,1
2016-01-21 21:00,2,0,0,0,0,0,0,0,0,0,0,0
2016-01-21 22:00,1,1,0,0,0,0,0,0,0,0,0,1
2016-01-21 23:00,8,0,0,0,0,0,0,0,0,0,0,0
2016-01-22 00:00,1,1,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2016-02-04 03:00,16,2,7,6,3,15,0,0,0,1,0,0
2016-02-04 04:00,15,0,4,1,0,15,0,0,0,0,0,1
2016-02-04 05:00,17,1,4,3,5,15,0,0,0,0,1,0
2016-02-04 06:00,16,0,3,1,4,14,0,0,0,0,0,0
2016-02-04 07:00,17,0,6,3,3,16,0,0,0,0,0,0
2016-02-04 08:00,15,2,3,5,2,14,0,0,0,0,0,0
2016-02-04 09:00,19,0,3,2,0,16,0,0,0,0,0,0
2016-02-04 10:00,15,3,2,4,2,14,0,0,0,0,0,0
2016-02-04 11:00,17,2,3,1,4,16,0,0,0,0,0,0
2016-02-04 12:00,16,1,7,8,0,14,0,0,0,0,0,0
2016-02-04 13:00,16,0,5,3,4,16,0,0,0,0,0,0
2016-02-04 14:00,15,0,14,13,7,14,0,1,0,0,0,0
2016-02-04 15:00,17,0,13,6,2,17,0,1,0,0,0,0
2016-02-04 16:00,16,3,9,5,2,14,0,0,0,0,0,0
2016-02-04 17:00,16,3,4,1,3,16,0,0,0,0,0,0
2016-02-04 18:00,15,1,3,3,1,15,1,0,0,0,0,0
2016-02-04 19:00,10,1,5,3,2,11,0,0,0,1,0,0
2016-02-04 20:00,2,0,2,0,0,0,0,0,0,0,0,0
2016-02-04 21:00,1,0,4,5,0,1,0,0,0,0,0,2
2016-02-04 22:00,0,0,0,1,0,1,0,0,0,0,0,0
2016-02-04 23:00,5,1,2,0,6,0,3,0,0,0,0,0
2016-02-05 00:00,2,0,3,6,2,0,0,0,0,0,0,0
2016-02-05 01:00,2,1,6,2,0,0,0,0,0,0,0,0
2016-02-05 02:00,3,1,2,3,2,0,1,0,0,0,0,0
2016-02-05 03:00,1,1,0,1,1,0,1,0,0,0,0,0
2016-02-05 04:00,1,1,1,1,2,0,0,0,0,0,0,0
2016-02-05 05:00,2,1,2,0,3,0,0,0,0,0,0,0
2016-02-05 06:00,2,1,0,1,2,1,0,0,1,0,1,0
2016-02-05 07:00,3,1,1,1,1,0,0,0,0,0,0,0
2016-02-05 08:00,0,0,0,0,0,0,0,0,0,0,0,0

In [29]:
df1.to_csv('surgepricing.csv')